```{r Set WDir}
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
```

```{r Imports}
# install.packages("Rcpp")
# install.packages("DBI")
# install.packages("RPostgres")
library(plyr)
library(RPostgres)
library(DBI)
library(tidyverse)
library(ggmap)
library(sqldf)
library(sf)
library(mapview)
```

```{r API}
# ?register_google
register_google(key=Sys.getenv("Google_Maps_Platform_API_Key"))
```

```{r DB connection - need to point to prod}
con <- dbConnect(RPostgres::Postgres(), 
                 host="localhost",
                 port="5432",
                 dbname="REI_Stage",
                 user="postgres",
                 password=rstudioapi::askForPassword("Database password"))

# dbExistsTable(con, "factListings")
```

```{r Get data}
# df_factListings <- dbGetQuery(con, "
# 
# SELECT 
# * 
# FROM 
# public.\"factListings\"
# ;
# 
# ")

dimProperty <- dbGetQuery(con, "

SELECT 
* 
FROM 
public.\"dimProperty\"
;

")

dimProperty
```

```{r Get existing geocoded values from cache}
dimProperty_fll <- read.csv("geocoded_loc_ref.csv")
dimProperty_fll
```

```{r RUN THIS IF NO CACHE FILE}
# dimProperty_fll <- mutate_geocode(subset(dimProperty, select=c("full_address")), full_address)
# colnames(dimProperty_fll) <- c("full_address", "longitude", "latitude")
# 
## geocode failed:
# sqldf("
#           SELECT
#           *
#           FROM
#           dimProperty_fll
#           WHERE
#           (longitude IS NULL AND latitude IS NULL)
#           ;
#           ")
# 
# # save scrape
# write.csv(dimProperty_fll,
# "C:/Users/User/Documents/FINANCES_CAREER/ONLINE_BUSINESS/Backend_API_v2/eda/geocoded_loc_ref.csv",
# row.names=FALSE)
```

```{r Comp between cached and dimProp}
dim(dimProperty)[1]
dim(dimProperty_fll)[1]
```

```{r View addresses not in cache to geocode}
# to geocode includes:
# - previously failed-to-geocode records (not written to cache file)
# - new properties recently added to dimProperty

# may need to add failures to cache if always fail to geocode as this may 
# cause slow processing times as the dimension grows

to_geocode <- sqldf("
          SELECT
          full_address
          FROM
          dimProperty
          
          EXCEPT
          
          SELECT
          full_address
          FROM
          dimProperty_fll
          ;
          ")
to_geocode
```
```{r test}
dft <- data.frame(
  address = c("1600 Pennsylvania Avenue, Washington DC", "", "houston texas", "nonexistent addr"),
  stringsAsFactors = FALSE
)

dft <- mutate_geocode(dft, address)
dft
```
```{r test2}
# geocode random 3 from dimProperty - issue is format of to_geocode
# dft2 <- mutate_geocode(
#   subset(to_geocode[sample(nrow(to_geocode), 3), ], select=c("full_address"))
#   ,full_address)
# colnames(dft2) <- c("full_address", "longitude", "latitude")
# dft2 <- to_geocode[sample(nrow(to_geocode), 3), ]
# dft2
# mutate_geocode(dft2, full_address)
```

```{r test3}
# subset(dimProperty[sample(nrow(dimProperty), 3), ], select=c("full_address"))
# dimProperty
```

```{r test4}
# dftest <- data.frame(to_geocode[sample(nrow(to_geocode), 3), ])
# colnames(dftest) <- c("full_address")
# dftest
# to_geocode
```

```{r test5}
# # geocode a subset
# # dftest <- data.frame(to_geocode[sample(nrow(to_geocode), 100), ], stringsAsFactors=FALSE)
# 
# # or geocode all
# dftest <- data.frame(to_geocode, stringsAsFactors=FALSE)
# 
# colnames(dftest) <- c("full_address")
# # dftest
# 
# dftestres <- mutate_geocode(dftest, full_address)
# dftestres
```

```{r to geocode}
# attempt to geocode to_geocode and reformat like cache
# 3 attempts to avoid API connectivity issues (needed?)
# r <- NULL
# attempt <- 0
# while(is.null(r) && attempt <= 3) {
#   attempt <- attempt + 1
#   try(
#     v <- mutate_geocode(
#       subset(to_geocode, select=c("full_address")),
#       full_address
#       )
#   )
# }
# try(
#   df_dimProperty_fll_new
# )

# single run - working
df_dimProperty_fll_new <- data.frame(to_geocode, stringsAsFactors=FALSE)
colnames(df_dimProperty_fll_new) <- c("full_address")
df_dimProperty_fll_new <- mutate_geocode(df_dimProperty_fll_new, full_address)
colnames(df_dimProperty_fll_new) <- c("full_address", "longitude", "latitude")
df_dimProperty_fll_new
```

```{r update cache accordingly }
if(exists("df_dimProperty_fll_new")){
  # non-empty = write
  # merge with cached if above results are non-empty 
  dimProperty_fll_merged <- merge(x=dimProperty_fll,
                                y=df_dimProperty_fll_new,
                                by="full_address",
                                all=TRUE)

  # reformat
  skew_rows <- which(!is.na(dimProperty_fll_merged[, 4]))
  
  # shift .y's left
  if(length(skew_rows) != 0){
    for(i in skew_rows){
    dimProperty_fll_merged[i, 2:3] <- dimProperty_fll_merged[i, 4:5]
    }
  }
  
  colnames(dimProperty_fll_merged)[2:3] <- c("longitude", "latitude")
  # discard old columnns
  dimProperty_fll_merged <- subset(dimProperty_fll_merged, 
                                   select=c("full_address", "longitude", "latitude"))
  
  # # update cache
  write.csv(
    dimProperty_fll_merged,"C:/Users/User/Documents/FINANCES_CAREER/ONLINE_BUSINESS/Backend_API_v2/eda/geocoded_loc_ref.csv",
    row.names=FALSE)
  
  # view new
  dimProperty_fll_merged
} else {
  print("No new geocoded data, not updating cache")
}
```

```{r read updated cache}
# this data ready for analysis, just need to exclude nulls (if applicable) for plot
df <- read.csv("geocoded_loc_ref.csv")
df
```

```{r create and view sf}
# remove nulls (if blanks in cache)
df <- sqldf("
          SELECT
          *
          FROM
          df
          WHERE
          (longitude IS NOT NULL OR latitude IS NOT NULL)
          ;
          ")
df
```

```{r}
# check that the geocoding done correctly with mapview
locations_sf <- st_as_sf(df, 
                         coords=c("longitude", "latitude"), 
                         crs=4326)
locations_sf
```

```{r POC map}
mapview(locations_sf)
```
```{r test next}
map <- get_googlemap(center = c(144, -30), zoom = 6)
ggmap(map)
# ggmap(map) +
# geom_point(data = locations, aes(x = lon, y = lat))
```

